### ISSUE TITLE
Error on activating "Analyze" in Firefox

### ISSUE THREAD

**Issue by MarioBatusic** [dequelabs/axe-core#1512]
Expectation: << Describe what you expect the product to do >>

Actual: << Describe what the product actually does >>
Throws Error on activating "Analyze" Button
Motivation: << Describe why you want the behavior to be changed >>

<pre><code>
axe-core version: 3.2.2
axe-webdriver, extension or other integration version: 3.8.0

Browser and Assistive Technology versions
Firefox 66.0.3
NVDA 2019-1
For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

Checked Page: https://www.fabasoft.com/de/loesungen/produktmanagement

Detailed Error:
@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77413
o@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77095
@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77745
o@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77095
@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77745
o@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77095
@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77745
o@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77095
@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77745
o@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77095
@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77745
o@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77095
@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:77745
j@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:93:60065
u/<@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:69:170370
u@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:69:170344
t.default/<@moz-extension://8f0eb4de-6797-4105-876c-278786c5061e/adapter.bundle.js:69:172614

**Comment by WilcoFiers** [comment]
Confirmed. Thank you for reporting @MarioBatusic! We'll look into it.

**Comment by straker** [comment]
Believe this was fixed by https://github.com/dequelabs/axe-core/pull/1577

**Comment by chandana7393** [comment]
Tested, unable to analyze the page  https://www.fabasoft.com/de/loesungen/produktmanagement using attest Firefox and Axe Firefox.
![attest_firefox_error](https://user-images.githubusercontent.com/45285854/59430383-bedf6880-8dff-11e9-8418-996d94366288.PNG)
![axe_firefox_error](https://user-images.githubusercontent.com/45285854/59430391-c3a41c80-8dff-11e9-84b4-861caacb8336.PNG)

**Tested Environment:**
Attest - 2.5.0.15720v
Axe - 3.8.0.14020v
Firefox - 66v
OS - Windows 10 64 bit.

**Comment by chandana7393** [comment]
@AdnoC please take a look at this issue.

**Comment by chandana7393** [comment]
Tested, the issue is still reproducing.
![Attest_firefox_error](https://user-images.githubusercontent.com/45285854/62941241-36774700-bdf3-11e9-910f-7719d8411030.PNG)
**Tested Environment:**
Attest - 2.6.1v
Axe - 3.8.1.22418v
Firefox - 68.0.1v
OS - Windows 10 64 bit.

**Comment by AdnoC** [comment]
The fix for this will be included in `axe-core@3.3.2`.

**Comment by scurker** [comment]
Tested with `axe-core` nightly in Firefox, and no issues. This should be fixed when we release `4.3.0`.

**Comment by scurker** [comment]
Tested again with `axe-core 3.5.0` and couldn't reproduce.

**Comment by padmavemulapati** [comment]
Verified for the same page, where issue reported,  https://www.fabasoft.com/de/loesungen/produktmanagement.
Verified versions, attest-extension(v2.8.0.04805) and axe-core(3.5.1)
not able to reproduce. Seeing the analysed results
![image](https://user-images.githubusercontent.com/47409579/74633625-09339900-5188-11ea-975b-1c6131475f24.png)
Also Analysed for one more test page, working fine 
![image](https://user-images.githubusercontent.com/47409579/74633525-cffb2900-5187-11ea-91d2-08ab8741ced4.png)
