### ISSUE TITLE
color-contrast does not support `mix-blend-mode: color | luminosity | saturation`

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#4170]
The following HTML produces an error of `"blendFunctions[blendMode] is not a function"`. Looks like we need to add the [color blend mode](https://www.w3.org/TR/compositing-1/#propdef-mix-blend-mode) to our [list of blend functions](https://github.com/dequelabs/axe-core/blob/develop/lib/commons/color/flatten-colors.js#L11).  We also need to add `luminosity` and `saturation`.

```html
<div style="mix-blend-mode: color;">Errors</div>
```

**Comment by kundan8239** [comment]
Is this fix available on npm ?

**Comment by straker** [comment]
@kundan8239 This hasn't been fixed yet. We hope to get it into the 4.9 release, but we don't have it groomed yet nor a schedule for when it will be released.

**Comment by Alpdog14** [comment]
This is still causing issues on my corporate website, when will this be resolved on Lighthouse tool? or when will it be updated? Like a date?

**Comment by straker** [comment]
@Alpdog14 We are planning the 4.9 release so can make sure to include this.

**Comment by Alpdog14** [comment]
@straker , do u know when Google Chrome will be releasing that 4.9 version of Axe-Core in its brower? because it is still showing a ! for accessibility when I run it

**Comment by straker** [comment]
I do not. Once we release 4.9 it'll still take awhile for Google to update Lighthouse and their products to ingest the changes.
